INSERT INTO libros (titulo, autor, cantidad) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 37);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('1984', 'George Orwell', 62);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Matar un ruiseñor', 'Harper Lee', 23);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 84);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('En busca del tiempo perdido', 'Marcel Proust', 71);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Ulises', 'James Joyce', 56);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El Gran Gatsby', 'F. Scott Fitzgerald', 45);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Moby-Dick', 'Herman Melville', 18);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Las dos torres', 'J.R.R. Tolkien', 78);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El corazón de las tinieblas', 'Joseph Conrad', 33);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Orgullo y prejuicio', 'Jane Austen', 70);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El retrato de Dorian Gray', 'Oscar Wilde', 9);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Crimen y castigo', 'Fyodor Dostoevsky', 91);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El extraño caso del Dr. Jekyll y Mr. Hyde', 'Robert Louis Stevenson', 15);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Mujer en punto cero', 'Nawal El Saadawi', 64);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Los juegos del hambre', 'Suzanne Collins', 88);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El Alquimista', 'Paulo Coelho', 77);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 53);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Crónica de una muerte anunciada', 'Gabriel García Márquez', 12);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El nombre de la rosa', 'Umberto Eco', 41);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Rayuela', 'Julio Cortázar', 60);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Los pilares de la Tierra', 'Ken Follett', 32);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Cumbres Borrascosas', 'Emily Brontë', 15);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Los hombres me explican cosas', 'Rebecca Solnit', 88);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Fahrenheit 451', 'Ray Bradbury', 77);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('La carretera', 'Cormac McCarthy', 46);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('La comunidad del anillo', 'J.R.R. Tolkien', 94);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Los miserables', 'Victor Hugo', 59);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('La sombra del viento', 'Carlos Ruiz Zafón', 67);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El lobo de mar', 'Jack London', 27);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('La Odisea', 'Homero', 35);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Cazadores de sombras', 'Cassandra Clare', 76);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Frankenstein', 'Mary Shelley', 13);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Los juegos de Ender', 'Orson Scott Card', 88);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('La naranja mecánica', 'Anthony Burgess', 42);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El retorno del rey', 'J.R.R. Tolkien', 86);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('El corredor del laberinto', 'James Dashner', 64);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Un mundo feliz', 'Aldous Huxley', 59);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Los hombres que no amaban a las mujeres', 'Stieg Larsson', 27);
INSERT INTO libros (titulo, autor, cantidad) VALUES ('Siddhartha', 'Hermann Hesse', 17);

INSERT INTO usuarios (nombre, apellido, email) VALUES ('Juan', 'Pérez', 'juan.perez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('María', 'Gómez', 'maria.gomez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Carlos', 'López', 'carlos.lopez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Ana', 'Rodríguez', 'ana.rodriguez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Luis', 'Martínez', 'luis.martinez@example.com');
